baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Hugo Project'
theme = "PaperMod"
# 1. 确保个人形象模式是关闭的（把文章列表召唤回来）
[params.profileMode]
    enabled = false

# 2. 在网站最左上角添加头像 Logo 和名字
[params.label]
    text = "TF"
    icon = "/images/002.jpg"
    iconHeight = 35

[params]
    showtoc = true
    tocopen = true

